apiVersion: apps/v1
kind: Deployment
metadata:
  name: asdsadasdas
  labels:
    app: asdsadasdas
  namespace: kube-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asdsadasdas
  template:
    metadata:
      labels:
        app: asdsadasdas
    spec:
      containers:
        - name: asdsadasdas
          image: acrworkflow1678733430647.azurecr.io/image-workflow-1678733430647:latest
          ports:
            - containerPort: 80