apiVersion: v1
kind: Service
metadata:
  name: asdsadasdas
  namespace: kube-public
spec:
  type: LoadBalancer
  selector:
    app: asdsadasdas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80